azure:
  activedirectory:
    b2c:
      tenant: cloudapporg
      client-id: f90544b9-49a4-4470-8963-bd5ac0965f46
      client-secret: wPER&96gn))U37IWmf61lse8
      reply-url: http://localhost:8080/oauth2/login
      logout-success-url: http://localhost:8080/
      user-flows:
        sign-up-or-sign-in: B2C_1_identity       
